---
- name: Deploy Cyber_Minibus to Ronin
  hosts: ronin
  become: yes
  gather_facts: yes

  vars:
    # --- Required/Recommended overrides ---
    jwt_secret: "CHANGE_ME_generate_a_strong_secret"
    vite_base_url: "http://localhost:3000/api"

    # --- Optional toggles ---
    client_build: false
    frontend_dev_enabled: true
    frontend_port: 5173
    server_vulnerable_sqli_mode: true
    server_vulnerable_mode: true
    client_vulnerable_ui_mode: true
    vite_currency: "$"

    # Paths and repo
    project_dir: "/home/{{ ansible_user }}/Cyber_Minibus"
    repo_url: "https://github.com/aintnoBaka7227/Cyber_Minibus.git"
    mongodb_port: 27017

  tasks:
    - name: Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: yes

    - name: Install base packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - apt-transport-https
          - git
          - unzip
        state: present

    - name: Install Node.js 20.x repo
      ansible.builtin.shell: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      args:
        executable: /bin/bash
      changed_when: false

    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present

    - name: Prepare Docker APT prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create keyrings directory for Docker
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Install Docker APT GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker APT repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        mode: "0644"

    - name: Update apt cache (Docker repo)
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker engine and plugins
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enable and start Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install docker-compose-plugin
      ansible.builtin.apt:
        name: docker-compose-plugin
        state: present

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Ensure project directory exists
      ansible.builtin.file:
        path: "{{ project_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Clone or update repo
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        version: main
        update: yes
        force: yes
        accept_hostkey: yes
      become_user: "{{ ansible_user }}"

    - name: Ensure server .env from template
      ansible.builtin.template:
        src: templates/server.env.j2
        dest: "{{ project_dir }}/server/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Ensure client .env from template
      ansible.builtin.template:
        src: templates/client.env.j2
        dest: "{{ project_dir }}/client/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Install server dependencies (npm install)
      ansible.builtin.shell: npm install --no-progress --omit=dev
      args:
        chdir: "{{ project_dir }}/server"
      become_user: "{{ ansible_user }}"

    - name: Install client dependencies (npm install)
      ansible.builtin.shell: npm install --no-progress
      args:
        chdir: "{{ project_dir }}/client"
      become_user: "{{ ansible_user }}"

    - name: Install systemd unit for Vite dev (optional)
      when: frontend_dev_enabled
      block:
        - name: Install frontend dev systemd unit
          ansible.builtin.template:
            src: templates/minibus-frontend-dev.service.j2
            dest: /etc/systemd/system/minibus-frontend-dev.service
            mode: "0644"

        - name: Reload systemd (frontend)
          ansible.builtin.systemd:
            daemon_reload: yes

        - name: Enable and start frontend dev service
          ansible.builtin.systemd:
            name: minibus-frontend-dev
            enabled: yes
            state: started

    - name: Build client
      when: client_build
      ansible.builtin.shell: npm run build
      args:
        chdir: "{{ project_dir }}/client"
      become_user: "{{ ansible_user }}"

    - name: Bring up MongoDB via Docker Compose
      ansible.builtin.shell: docker compose up -d
      args:
        chdir: "{{ project_dir }}"

    - name: Wait for Mongo port to be open
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: "{{ mongodb_port }}"
        delay: 2
        timeout: 60

    - name: Seed database once
      ansible.builtin.shell: |
        npm run seed && touch {{ project_dir }}/.seeded
      args:
        chdir: "{{ project_dir }}/server"
        creates: "{{ project_dir }}/.seeded"
      become_user: "{{ ansible_user }}"

    - name: Install systemd unit for backend
      ansible.builtin.template:
        src: templates/minibus-server.service.j2
        dest: /etc/systemd/system/minibus-server.service
        mode: "0644"

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start backend service
      ansible.builtin.systemd:
        name: minibus-server
        enabled: yes
        state: started

    - name: Verify backend is responding
      ansible.builtin.shell: |
        curl -sf http://localhost:3000 || true
      register: backend_check
      changed_when: false
      failed_when: false

    - name: Show backend check output
      ansible.builtin.debug:
        msg: "Backend check: {{ backend_check.stdout | default('') }}"
